version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "CODEBUILD_SRC_DIR = $CODEBUILD_SRC_DIR"
      - echo "Current directory structure:"
      - ls -la
      - echo "Checking for pom.xml:"
      - find . -name "pom.xml"
      - echo "Moving to directory with pom.xml"
      - cd bird-app
  build:
    commands:
      - echo Build started on `date`
      - echo "Current directory:"
      - pwd
      - echo "Directory contents:"
      - ls -la
      - mvn clean install -DskipTests
  post_build:
    commands:
      - echo Build completed on `date`
      - echo "Checking build output:"
      - ls -la target/

artifacts:
  base-directory: target
  files:
    - bird-app-0.0.2-SNAPSHOT.jar
  discard-paths: yes 